// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVqq98DjPX6YqInZOvwRmvW6hGtY-2T1I',
    appId: '1:262399623474:android:1275727a4ceb4af644972b',
    messagingSenderId: '262399623474',
    projectId: 'todos-e7069',
    databaseURL: 'https://todos-e7069-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todos-e7069.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2MdjqVyu_vRPWlzUQ8sEpO1zk1hTZ2Tk',
    appId: '1:262399623474:ios:bc0499b3a35c792444972b',
    messagingSenderId: '262399623474',
    projectId: 'todos-e7069',
    databaseURL: 'https://todos-e7069-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todos-e7069.appspot.com',
    iosBundleId: 'com.example.toDoUiFlutter',
  );
}
